### ISSUE TITLE
val.replace is not a function error on flutterwave card.

### ISSUE THREAD

**Issue by syntaxPriest** [Flutterwave/React-Native#57]
![Screenshot 2022-10-03 182827](https://user-images.githubusercontent.com/76406495/194838908-61166013-5c52-45b5-a5c6-89f94a6d8fa7.png)

I get this error for card payment on the flutterwave payment pop-up.

**Comment by kpose** [comment]
Hi @syntaxPriest , apologies for the setback, you can now successfully make payment. Please do try again and revert if you encounter any other issue

**Comment by syntaxPriest** [comment]
Thank you @kpose
