### ISSUE TITLE
customButton props.onPress stopped working

### ISSUE THREAD

**Issue by Zeusmist** [Flutterwave/React-Native#62]
Hi guys,
All of a sudden the onPress function passed through props in customButton stopped opening the flutterwave payment modal.

Is there a limit to usage? I'm currently using test env.

**Comment by mwelwankuta** [comment]
usually this could be because of missing options could you confirm that you have a correct options, including the customer email which seems to be a requied field
```js
options={{
   payment_options: "mobile_money_zambia",
   tx_ref: Date.now().toString(),
   authorization: "YOUR AUTHORIZATION TOKEN",
   amount: orderTotal,
   currency: "ZMW",
   customer: {
     email: "customeremail@email.com",
     name: "customer name",
     phonenumber: "",
   },
}}
```

**Comment by mwelwankuta** [comment]
> @mwelwankuta It works now. It happened around the recent hack. I think FLW servers denied the request. Thanks for the support.

you're welcome.
